[package]
authors = ['Mangata team']
name = "random-seed-runtime-api"
version = "2.0.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
sp-api = { version = '2.0.0', default-features = false, path = "../../../primitives/api" }
pallet-random-seed = { path="../../random-seed", version = '2.0.0', default-features = false }

[features]
default = ["std"]
std = [
    "sp-api/std",
]
