[package]
name = "sp-ignore-tx"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME Timestamp Module"
documentation = "https://docs.rs/pallet-timestamp"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
log = "0.4.8"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
sp-runtime = { version = "2.0.0", default-features = false, path = "../runtime"}
sp-inherents = { version = "2.0.0", default-features = false, path = "../inherents"}

[dev-dependencies]
sp-io ={ version = "2.0.0", path="../io" }
sp-core = { version = "2.0.0" , path="../core"}

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"serde",
]
