[package]
name = "pallet-random-seed"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME Timestamp Module"
documentation = "https://docs.rs/pallet-timestamp"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
log = "0.4.8"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
sp-io = { version = "2.0.0", default-features = false, optional = true , path = "../../primitives/io"}
sp-core = { version = "2.0.0", default-features = false, path = "../../primitives/core"}
sp-runtime = { version = "2.0.0", default-features = false , path = "../../primitives/runtime"}
sp-inherents = { version = "2.0.0", default-features = false , path = "../../primitives/inherents"}
frame-support = { version = "2.0.0", default-features = false , path = "../../frame/support"}
frame-system = { version = "2.0.0", default-features = false , path = "../../frame/system"}
impl-trait-for-tuples = "0.1.3"

[dev-dependencies]
sp-io ={ version = "2.0.0" , path = "../../primitives/io"}
sp-core = { version = "2.0.0" , path = "../../primitives/core"}

[features]
default = ["std"]
std = [
	"sp-inherents/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"serde",
	"frame-system/std",
]
